broker:
  host: "ra216119.ala.eu-central-1.emqxsl.com"
  port: 8883
  tls: true
  username: "waladi_pi"       # <-- set the username you created in EMQX console
  password: "CHANGE_ME"       # <-- set the password you created in EMQX console

client:
  keepalive: 30
  device_id: "waladi_pi"
